#!/usr/bin/env python3
"""Generates the third-party license notices shown on the About page.

Lists the crates linked into the app (cargo tree without dev, build and
proc-macro dependencies, for the device target) and the Rust standard
library, and takes each license text from the vendored sources. Where a
crate offers a choice, SailToken uses the MIT terms.

Usage: tools/gen-third-party-licenses.py          # rewrite the file
       tools/gen-third-party-licenses.py --check  # fail if it is outdated
"""

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "qml" / "pages" / "thirdparty.js"
TARGET = "aarch64-unknown-linux-gnu"
# The Rust toolchain of the SDK target; its standard library is linked in.
RUST_TOOLCHAIN = "1.75"
# Preferred license files, MIT terms first.
LICENSE_FILES = ["LICENSE-MIT", "LICENSE-MIT.md", "LICENSE", "LICENSE.md"]
# Licenses other than MIT, each checked by hand to be permissive.
CHOSEN = {"BSD-3-Clause", "ISC", "Zlib"}


def linked_crates():
    output = subprocess.run(
        ["cargo", "tree", "--manifest-path", str(ROOT / "core/Cargo.toml"), "--offline",
         "--edges", "normal,no-proc-macro", "--target", TARGET, "--prefix", "none",
         "--format", "{p}|{l}"],
        check=True, capture_output=True, text=True).stdout
    crates = {}
    for line in output.splitlines():
        package, license_expression = line.replace(" (*)", "").split("|", 1)
        name, version = package.split()[:2]
        if name != "sailtoken-core":
            crates[(name, version.lstrip("v"))] = license_expression.strip()
    return sorted(crates.items())


def chosen_licenses(name, expression):
    """The terms SailToken uses: MIT where offered, otherwise only what
    CHOSEN lists. Every part of an AND expression applies, such as rqrr's
    "(MIT OR Apache-2.0) AND ISC" for the code it ported from quirc."""
    chosen = []
    for part in expression.split(" AND "):
        part = part.strip().strip("()")
        if "MIT" in re.split(r"[\s()/]+", part):
            chosen.append("MIT")
        elif part in CHOSEN:
            chosen.append(part)
        else:
            sys.exit(f"{name}: no MIT terms in {part!r}; check the license and add it to CHOSEN")
    return chosen


def rust_license():
    sysroot = subprocess.run(["rustc", f"+{RUST_TOOLCHAIN}", "--print", "sysroot"],
                             check=True, capture_output=True, text=True).stdout.strip()
    return pathlib.Path(sysroot) / "share/doc/rust/LICENSE-MIT"


def license_text(name, version, license_id):
    directory = ROOT / "core/vendor" / f"{name}-{version}"
    candidates = LICENSE_FILES
    if license_id != "MIT":
        candidates = [f"LICENSE-{license_id}", f"LICENSE-{license_id}.md", "LICENSE", "LICENSE.md"]
    for file_name in candidates:
        path = directory / file_name
        if path.is_file():
            return path.read_text(encoding="utf-8").strip()
    sys.exit(f"no {license_id} license file for {name} {version} in {directory}")


def generate():
    texts = []
    packages = []

    def text_index(text):
        if text not in texts:
            texts.append(text)
        return texts.index(text)

    for (name, version), expression in linked_crates():
        licenses = chosen_licenses(name, expression)
        text = "\n\n".join(license_text(name, version, license_id) for license_id in licenses)
        packages.append({
            "name": name,
            "version": version,
            "license": " AND ".join(licenses),
            "text": text_index(text),
        })
    packages.append({
        "name": "Rust standard library",
        "version": RUST_TOOLCHAIN,
        "license": "MIT",
        "text": text_index(rust_license().read_text(encoding="utf-8").strip()),
    })
    return (".pragma library\n"
            "// Generated by tools/gen-third-party-licenses.py; do not edit.\n"
            f"var packages = {json.dumps(packages, indent=1, ensure_ascii=False)}\n"
            f"var texts = {json.dumps(texts, indent=1, ensure_ascii=False)}\n")


def main():
    content = generate()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            sys.exit(f"{OUTPUT.relative_to(ROOT)} is outdated; run {sys.argv[0]}")
        return
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
